---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# autoresid

<!-- badges: start -->
<!-- badges: end -->

The autoresid package performs model diagnostics by checking for dependence
among the estimated residuals.

## Installation

You can install the development version of autoresid like so:

``` r
pak::pkg_install("leonfernandes/autoresid")
```

## Example

```{r demo}
# load packages
library(autoresid)
library(fable)
library(smpspltools)
library(tsibble)

# simulate i.i.d. data
data <-
  tsibble(x = rnorm(100), date = Sys.Date() + 0:99, index = date)

# Consider fitting an AR(1) model
fit <-
  data |>
  estimate(ARIMA(x ~ pdq(1, 0, 0) + PDQ(0, 0, 0)))

# Extract arima object from fitted model
fit_arima <- smpspltools::extract_model(fit)

# Get residuals
autoresid(fit_arima, data, "x")
```